"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.sequelize = void 0;
const sequelize_1 = __importDefault(require("sequelize"));
const config_js_1 = __importDefault(require("../config/config.js"));
const user_js_1 = __importDefault(require("./user.js"));
const alarm_js_1 = __importDefault(require("./alarm.js"));
const bookmark_js_1 = __importDefault(require("./bookmark.js"));
const Box_js_1 = __importDefault(require("./Box.js"));
const memo_js_1 = __importDefault(require("./memo.js"));
const env = process.env.NODE_ENV || "development";
const config = config_js_1.default[env];
exports.sequelize = new sequelize_1.default.Sequelize(config.database, config.username, config.password, config);
alarm_js_1.default.initiate(exports.sequelize);
bookmark_js_1.default.initiate(exports.sequelize);
Box_js_1.default.initiate(exports.sequelize);
memo_js_1.default.initiate(exports.sequelize);
user_js_1.default.initiate(exports.sequelize);
alarm_js_1.default.associate();
bookmark_js_1.default.associate();
Box_js_1.default.associate();
memo_js_1.default.associate();
user_js_1.default.associate();
